/**
 * قائمة الدول لمنتقي رقم الهاتف.
 *
 * وُلِّدت من بيانات `react-native-country-picker-modal` لأنها تحمل رموز
 * الاتصال كاملةً، وأُضيفت إليها الأسماء العربية — المكتبة تترجم إلى
 * 18 لغة ليس بينها العربية، فبحث المستخدم بالعربية كان لا يُرجع شيئًا.
 *
 * الدول العربية والجوار ووجهات الاغتراب الرئيسية لها أسماء عربية
 * مكتوبة؛ البقية تُعرض بالإنجليزية وتبقى قابلة للبحث بها وبرمز الاتصال.
 *
 * الترتيب: الأقرب للمستخدم أولًا (العراق ثم الخليج والشام) ثم البقية
 * أبجديًا — البحث في قائمة من 200 دولة يبدأ عادةً بالأقرب.
 */

export interface Country {
  /** رمز ISO 3166-1 alpha-2 */
  code: string;
  /** رمز الاتصال الدولي مع + */
  dial: string;
  en: string;
  ar: string;
}

export const COUNTRIES: Country[] = [
  { code: 'IQ', dial: '+964', en: "Iraq", ar: "العراق" },
  { code: 'SA', dial: '+966', en: "Saudi Arabia", ar: "السعودية" },
  { code: 'AE', dial: '+971', en: "United Arab Emirates", ar: "الإمارات" },
  { code: 'KW', dial: '+965', en: "Kuwait", ar: "الكويت" },
  { code: 'QA', dial: '+974', en: "Qatar", ar: "قطر" },
  { code: 'BH', dial: '+973', en: "Bahrain", ar: "البحرين" },
  { code: 'OM', dial: '+968', en: "Oman", ar: "عُمان" },
  { code: 'JO', dial: '+962', en: "Jordan", ar: "الأردن" },
  { code: 'SY', dial: '+963', en: "Syria", ar: "سوريا" },
  { code: 'LB', dial: '+961', en: "Lebanon", ar: "لبنان" },
  { code: 'PS', dial: '+970', en: "Palestine", ar: "فلسطين" },
  { code: 'EG', dial: '+20', en: "Egypt", ar: "مصر" },
  { code: 'TR', dial: '+90', en: "Turkey", ar: "تركيا" },
  { code: 'IR', dial: '+98', en: "Iran", ar: "إيران" },
  { code: 'US', dial: '+1', en: "United States", ar: "الولايات المتحدة" },
  { code: 'GB', dial: '+44', en: "United Kingdom", ar: "المملكة المتحدة" },
  { code: 'DE', dial: '+49', en: "Germany", ar: "ألمانيا" },
  { code: 'SE', dial: '+46', en: "Sweden", ar: "السويد" },
  { code: 'AF', dial: '+93', en: "Afghanistan", ar: "أفغانستان" },
  { code: 'AL', dial: '+355', en: "Albania", ar: "ألبانيا" },
  { code: 'DZ', dial: '+213', en: "Algeria", ar: "الجزائر" },
  { code: 'AS', dial: '+1684', en: "American Samoa", ar: "American Samoa" },
  { code: 'AD', dial: '+376', en: "Andorra", ar: "Andorra" },
  { code: 'AO', dial: '+244', en: "Angola", ar: "Angola" },
  { code: 'AI', dial: '+1264', en: "Anguilla", ar: "Anguilla" },
  { code: 'AG', dial: '+1268', en: "Antigua and Barbuda", ar: "Antigua and Barbuda" },
  { code: 'AR', dial: '+54', en: "Argentina", ar: "الأرجنتين" },
  { code: 'AM', dial: '+374', en: "Armenia", ar: "أرمينيا" },
  { code: 'AW', dial: '+297', en: "Aruba", ar: "Aruba" },
  { code: 'AU', dial: '+61', en: "Australia", ar: "أستراليا" },
  { code: 'AT', dial: '+43', en: "Austria", ar: "النمسا" },
  { code: 'AZ', dial: '+994', en: "Azerbaijan", ar: "أذربيجان" },
  { code: 'BS', dial: '+1242', en: "Bahamas", ar: "Bahamas" },
  { code: 'BD', dial: '+880', en: "Bangladesh", ar: "بنغلاديش" },
  { code: 'BB', dial: '+1246', en: "Barbados", ar: "Barbados" },
  { code: 'BY', dial: '+375', en: "Belarus", ar: "Belarus" },
  { code: 'BE', dial: '+32', en: "Belgium", ar: "بلجيكا" },
  { code: 'BZ', dial: '+501', en: "Belize", ar: "Belize" },
  { code: 'BJ', dial: '+229', en: "Benin", ar: "Benin" },
  { code: 'BM', dial: '+1441', en: "Bermuda", ar: "Bermuda" },
  { code: 'BT', dial: '+975', en: "Bhutan", ar: "Bhutan" },
  { code: 'BO', dial: '+591', en: "Bolivia", ar: "Bolivia" },
  { code: 'BA', dial: '+387', en: "Bosnia and Herzegovina", ar: "Bosnia and Herzegovina" },
  { code: 'BW', dial: '+267', en: "Botswana", ar: "Botswana" },
  { code: 'BR', dial: '+55', en: "Brazil", ar: "البرازيل" },
  { code: 'IO', dial: '+246', en: "British Indian Ocean Territory", ar: "British Indian Ocean Territory" },
  { code: 'VG', dial: '+1284', en: "British Virgin Islands", ar: "British Virgin Islands" },
  { code: 'BN', dial: '+673', en: "Brunei", ar: "Brunei" },
  { code: 'BG', dial: '+359', en: "Bulgaria", ar: "Bulgaria" },
  { code: 'BF', dial: '+226', en: "Burkina Faso", ar: "Burkina Faso" },
  { code: 'BI', dial: '+257', en: "Burundi", ar: "Burundi" },
  { code: 'KH', dial: '+855', en: "Cambodia", ar: "Cambodia" },
  { code: 'CM', dial: '+237', en: "Cameroon", ar: "Cameroon" },
  { code: 'CA', dial: '+1', en: "Canada", ar: "كندا" },
  { code: 'CV', dial: '+238', en: "Cape Verde", ar: "Cape Verde" },
  { code: 'BQ', dial: '+599', en: "Caribbean Netherlands", ar: "Caribbean Netherlands" },
  { code: 'KY', dial: '+1345', en: "Cayman Islands", ar: "Cayman Islands" },
  { code: 'CF', dial: '+236', en: "Central African Republic", ar: "Central African Republic" },
  { code: 'TD', dial: '+235', en: "Chad", ar: "Chad" },
  { code: 'CL', dial: '+56', en: "Chile", ar: "تشيلي" },
  { code: 'CN', dial: '+86', en: "China", ar: "الصين" },
  { code: 'CX', dial: '+61', en: "Christmas Island", ar: "Christmas Island" },
  { code: 'CC', dial: '+61', en: "Cocos (Keeling) Islands", ar: "Cocos (Keeling) Islands" },
  { code: 'CO', dial: '+57', en: "Colombia", ar: "كولومبيا" },
  { code: 'KM', dial: '+269', en: "Comoros", ar: "جزر القمر" },
  { code: 'CK', dial: '+682', en: "Cook Islands", ar: "Cook Islands" },
  { code: 'CR', dial: '+506', en: "Costa Rica", ar: "Costa Rica" },
  { code: 'HR', dial: '+385', en: "Croatia", ar: "Croatia" },
  { code: 'CU', dial: '+53', en: "Cuba", ar: "Cuba" },
  { code: 'CW', dial: '+5999', en: "Curaçao", ar: "Curaçao" },
  { code: 'CY', dial: '+357', en: "Cyprus", ar: "قبرص" },
  { code: 'CZ', dial: '+420', en: "Czechia", ar: "التشيك" },
  { code: 'CD', dial: '+243', en: "DR Congo", ar: "DR Congo" },
  { code: 'DK', dial: '+45', en: "Denmark", ar: "الدنمارك" },
  { code: 'DJ', dial: '+253', en: "Djibouti", ar: "جيبوتي" },
  { code: 'DM', dial: '+1767', en: "Dominica", ar: "Dominica" },
  { code: 'DO', dial: '+1809', en: "Dominican Republic", ar: "Dominican Republic" },
  { code: 'EC', dial: '+593', en: "Ecuador", ar: "Ecuador" },
  { code: 'SV', dial: '+503', en: "El Salvador", ar: "El Salvador" },
  { code: 'GQ', dial: '+240', en: "Equatorial Guinea", ar: "Equatorial Guinea" },
  { code: 'ER', dial: '+291', en: "Eritrea", ar: "Eritrea" },
  { code: 'EE', dial: '+372', en: "Estonia", ar: "Estonia" },
  { code: 'SZ', dial: '+268', en: "Eswatini", ar: "Eswatini" },
  { code: 'ET', dial: '+251', en: "Ethiopia", ar: "إثيوبيا" },
  { code: 'FK', dial: '+500', en: "Falkland Islands", ar: "Falkland Islands" },
  { code: 'FO', dial: '+298', en: "Faroe Islands", ar: "Faroe Islands" },
  { code: 'FJ', dial: '+679', en: "Fiji", ar: "Fiji" },
  { code: 'FI', dial: '+358', en: "Finland", ar: "فنلندا" },
  { code: 'FR', dial: '+33', en: "France", ar: "فرنسا" },
  { code: 'GF', dial: '+594', en: "French Guiana", ar: "French Guiana" },
  { code: 'PF', dial: '+689', en: "French Polynesia", ar: "French Polynesia" },
  { code: 'GA', dial: '+241', en: "Gabon", ar: "Gabon" },
  { code: 'GM', dial: '+220', en: "Gambia", ar: "Gambia" },
  { code: 'GE', dial: '+995', en: "Georgia", ar: "جورجيا" },
  { code: 'GH', dial: '+233', en: "Ghana", ar: "Ghana" },
  { code: 'GI', dial: '+350', en: "Gibraltar", ar: "Gibraltar" },
  { code: 'GR', dial: '+30', en: "Greece", ar: "اليونان" },
  { code: 'GL', dial: '+299', en: "Greenland", ar: "Greenland" },
  { code: 'GD', dial: '+1473', en: "Grenada", ar: "Grenada" },
  { code: 'GP', dial: '+590', en: "Guadeloupe", ar: "Guadeloupe" },
  { code: 'GU', dial: '+1671', en: "Guam", ar: "Guam" },
  { code: 'GT', dial: '+502', en: "Guatemala", ar: "Guatemala" },
  { code: 'GG', dial: '+44', en: "Guernsey", ar: "Guernsey" },
  { code: 'GN', dial: '+224', en: "Guinea", ar: "Guinea" },
  { code: 'GW', dial: '+245', en: "Guinea-Bissau", ar: "Guinea-Bissau" },
  { code: 'GY', dial: '+592', en: "Guyana", ar: "Guyana" },
  { code: 'HT', dial: '+509', en: "Haiti", ar: "Haiti" },
  { code: 'HN', dial: '+504', en: "Honduras", ar: "Honduras" },
  { code: 'HK', dial: '+852', en: "Hong Kong", ar: "Hong Kong" },
  { code: 'HU', dial: '+36', en: "Hungary", ar: "المجر" },
  { code: 'IS', dial: '+354', en: "Iceland", ar: "Iceland" },
  { code: 'IN', dial: '+91', en: "India", ar: "الهند" },
  { code: 'ID', dial: '+62', en: "Indonesia", ar: "إندونيسيا" },
  { code: 'IE', dial: '+353', en: "Ireland", ar: "أيرلندا" },
  { code: 'IM', dial: '+44', en: "Isle of Man", ar: "Isle of Man" },
  { code: 'IL', dial: '+972', en: "Israel", ar: "Israel" },
  { code: 'IT', dial: '+39', en: "Italy", ar: "إيطاليا" },
  { code: 'CI', dial: '+225', en: "Ivory Coast", ar: "Ivory Coast" },
  { code: 'JM', dial: '+1876', en: "Jamaica", ar: "Jamaica" },
  { code: 'JP', dial: '+81', en: "Japan", ar: "اليابان" },
  { code: 'JE', dial: '+44', en: "Jersey", ar: "Jersey" },
  { code: 'KZ', dial: '+7', en: "Kazakhstan", ar: "Kazakhstan" },
  { code: 'KE', dial: '+254', en: "Kenya", ar: "كينيا" },
  { code: 'KI', dial: '+686', en: "Kiribati", ar: "Kiribati" },
  { code: 'XK', dial: '+383', en: "Kosovo", ar: "Kosovo" },
  { code: 'KG', dial: '+996', en: "Kyrgyzstan", ar: "Kyrgyzstan" },
  { code: 'LA', dial: '+856', en: "Laos", ar: "Laos" },
  { code: 'LV', dial: '+371', en: "Latvia", ar: "Latvia" },
  { code: 'LS', dial: '+266', en: "Lesotho", ar: "Lesotho" },
  { code: 'LR', dial: '+231', en: "Liberia", ar: "Liberia" },
  { code: 'LY', dial: '+218', en: "Libya", ar: "ليبيا" },
  { code: 'LI', dial: '+423', en: "Liechtenstein", ar: "Liechtenstein" },
  { code: 'LT', dial: '+370', en: "Lithuania", ar: "Lithuania" },
  { code: 'LU', dial: '+352', en: "Luxembourg", ar: "Luxembourg" },
  { code: 'MO', dial: '+853', en: "Macau", ar: "Macau" },
  { code: 'MK', dial: '+389', en: "Macedonia", ar: "Macedonia" },
  { code: 'MG', dial: '+261', en: "Madagascar", ar: "Madagascar" },
  { code: 'MW', dial: '+265', en: "Malawi", ar: "Malawi" },
  { code: 'MY', dial: '+60', en: "Malaysia", ar: "ماليزيا" },
  { code: 'MV', dial: '+960', en: "Maldives", ar: "Maldives" },
  { code: 'ML', dial: '+223', en: "Mali", ar: "Mali" },
  { code: 'MT', dial: '+356', en: "Malta", ar: "مالطا" },
  { code: 'MH', dial: '+692', en: "Marshall Islands", ar: "Marshall Islands" },
  { code: 'MQ', dial: '+596', en: "Martinique", ar: "Martinique" },
  { code: 'MR', dial: '+222', en: "Mauritania", ar: "موريتانيا" },
  { code: 'MU', dial: '+230', en: "Mauritius", ar: "Mauritius" },
  { code: 'YT', dial: '+262', en: "Mayotte", ar: "Mayotte" },
  { code: 'MX', dial: '+52', en: "Mexico", ar: "المكسيك" },
  { code: 'FM', dial: '+691', en: "Micronesia", ar: "Micronesia" },
  { code: 'MD', dial: '+373', en: "Moldova", ar: "Moldova" },
  { code: 'MC', dial: '+377', en: "Monaco", ar: "Monaco" },
  { code: 'MN', dial: '+976', en: "Mongolia", ar: "Mongolia" },
  { code: 'ME', dial: '+382', en: "Montenegro", ar: "Montenegro" },
  { code: 'MS', dial: '+1664', en: "Montserrat", ar: "Montserrat" },
  { code: 'MA', dial: '+212', en: "Morocco", ar: "المغرب" },
  { code: 'MZ', dial: '+258', en: "Mozambique", ar: "Mozambique" },
  { code: 'MM', dial: '+95', en: "Myanmar", ar: "Myanmar" },
  { code: 'NA', dial: '+264', en: "Namibia", ar: "Namibia" },
  { code: 'NR', dial: '+674', en: "Nauru", ar: "Nauru" },
  { code: 'NP', dial: '+977', en: "Nepal", ar: "Nepal" },
  { code: 'NL', dial: '+31', en: "Netherlands", ar: "هولندا" },
  { code: 'NC', dial: '+687', en: "New Caledonia", ar: "New Caledonia" },
  { code: 'NZ', dial: '+64', en: "New Zealand", ar: "نيوزيلندا" },
  { code: 'NI', dial: '+505', en: "Nicaragua", ar: "Nicaragua" },
  { code: 'NE', dial: '+227', en: "Niger", ar: "Niger" },
  { code: 'NG', dial: '+234', en: "Nigeria", ar: "نيجيريا" },
  { code: 'NU', dial: '+683', en: "Niue", ar: "Niue" },
  { code: 'NF', dial: '+672', en: "Norfolk Island", ar: "Norfolk Island" },
  { code: 'KP', dial: '+850', en: "North Korea", ar: "North Korea" },
  { code: 'MP', dial: '+1670', en: "Northern Mariana Islands", ar: "Northern Mariana Islands" },
  { code: 'NO', dial: '+47', en: "Norway", ar: "النرويج" },
  { code: 'PK', dial: '+92', en: "Pakistan", ar: "باكستان" },
  { code: 'PW', dial: '+680', en: "Palau", ar: "Palau" },
  { code: 'PA', dial: '+507', en: "Panama", ar: "Panama" },
  { code: 'PG', dial: '+675', en: "Papua New Guinea", ar: "Papua New Guinea" },
  { code: 'PY', dial: '+595', en: "Paraguay", ar: "Paraguay" },
  { code: 'PE', dial: '+51', en: "Peru", ar: "Peru" },
  { code: 'PH', dial: '+63', en: "Philippines", ar: "الفلبين" },
  { code: 'PN', dial: '+64', en: "Pitcairn Islands", ar: "Pitcairn Islands" },
  { code: 'PL', dial: '+48', en: "Poland", ar: "بولندا" },
  { code: 'PT', dial: '+351', en: "Portugal", ar: "البرتغال" },
  { code: 'PR', dial: '+1787', en: "Puerto Rico", ar: "Puerto Rico" },
  { code: 'CG', dial: '+242', en: "Republic of the Congo", ar: "Republic of the Congo" },
  { code: 'RO', dial: '+40', en: "Romania", ar: "رومانيا" },
  { code: 'RU', dial: '+7', en: "Russia", ar: "روسيا" },
  { code: 'RW', dial: '+250', en: "Rwanda", ar: "Rwanda" },
  { code: 'RE', dial: '+262', en: "Réunion", ar: "Réunion" },
  { code: 'BL', dial: '+590', en: "Saint Barthélemy", ar: "Saint Barthélemy" },
  { code: 'SH', dial: '+290', en: "Saint Helena, Ascension and Tristan da Cunha", ar: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: 'KN', dial: '+1869', en: "Saint Kitts and Nevis", ar: "Saint Kitts and Nevis" },
  { code: 'LC', dial: '+1758', en: "Saint Lucia", ar: "Saint Lucia" },
  { code: 'MF', dial: '+590', en: "Saint Martin", ar: "Saint Martin" },
  { code: 'PM', dial: '+508', en: "Saint Pierre and Miquelon", ar: "Saint Pierre and Miquelon" },
  { code: 'VC', dial: '+1784', en: "Saint Vincent and the Grenadines", ar: "Saint Vincent and the Grenadines" },
  { code: 'WS', dial: '+685', en: "Samoa", ar: "Samoa" },
  { code: 'SM', dial: '+378', en: "San Marino", ar: "San Marino" },
  { code: 'SN', dial: '+221', en: "Senegal", ar: "Senegal" },
  { code: 'RS', dial: '+381', en: "Serbia", ar: "صربيا" },
  { code: 'SC', dial: '+248', en: "Seychelles", ar: "Seychelles" },
  { code: 'SL', dial: '+232', en: "Sierra Leone", ar: "Sierra Leone" },
  { code: 'SG', dial: '+65', en: "Singapore", ar: "سنغافورة" },
  { code: 'SX', dial: '+1721', en: "Sint Maarten", ar: "Sint Maarten" },
  { code: 'SK', dial: '+421', en: "Slovakia", ar: "Slovakia" },
  { code: 'SI', dial: '+386', en: "Slovenia", ar: "Slovenia" },
  { code: 'SB', dial: '+677', en: "Solomon Islands", ar: "Solomon Islands" },
  { code: 'SO', dial: '+252', en: "Somalia", ar: "الصومال" },
  { code: 'ZA', dial: '+27', en: "South Africa", ar: "جنوب أفريقيا" },
  { code: 'GS', dial: '+500', en: "South Georgia", ar: "South Georgia" },
  { code: 'KR', dial: '+82', en: "South Korea", ar: "كوريا الجنوبية" },
  { code: 'SS', dial: '+211', en: "South Sudan", ar: "South Sudan" },
  { code: 'ES', dial: '+34', en: "Spain", ar: "إسبانيا" },
  { code: 'LK', dial: '+94', en: "Sri Lanka", ar: "Sri Lanka" },
  { code: 'SD', dial: '+249', en: "Sudan", ar: "السودان" },
  { code: 'SR', dial: '+597', en: "Suriname", ar: "Suriname" },
  { code: 'SJ', dial: '+4779', en: "Svalbard and Jan Mayen", ar: "Svalbard and Jan Mayen" },
  { code: 'CH', dial: '+41', en: "Switzerland", ar: "سويسرا" },
  { code: 'ST', dial: '+239', en: "São Tomé and Príncipe", ar: "São Tomé and Príncipe" },
  { code: 'TW', dial: '+886', en: "Taiwan", ar: "Taiwan" },
  { code: 'TJ', dial: '+992', en: "Tajikistan", ar: "Tajikistan" },
  { code: 'TZ', dial: '+255', en: "Tanzania", ar: "Tanzania" },
  { code: 'TH', dial: '+66', en: "Thailand", ar: "تايلاند" },
  { code: 'TL', dial: '+670', en: "Timor-Leste", ar: "Timor-Leste" },
  { code: 'TG', dial: '+228', en: "Togo", ar: "Togo" },
  { code: 'TK', dial: '+690', en: "Tokelau", ar: "Tokelau" },
  { code: 'TO', dial: '+676', en: "Tonga", ar: "Tonga" },
  { code: 'TT', dial: '+1868', en: "Trinidad and Tobago", ar: "Trinidad and Tobago" },
  { code: 'TN', dial: '+216', en: "Tunisia", ar: "تونس" },
  { code: 'TM', dial: '+993', en: "Turkmenistan", ar: "Turkmenistan" },
  { code: 'TC', dial: '+1649', en: "Turks and Caicos Islands", ar: "Turks and Caicos Islands" },
  { code: 'TV', dial: '+688', en: "Tuvalu", ar: "Tuvalu" },
  { code: 'UG', dial: '+256', en: "Uganda", ar: "Uganda" },
  { code: 'UA', dial: '+380', en: "Ukraine", ar: "أوكرانيا" },
  { code: 'VI', dial: '+1340', en: "United States Virgin Islands", ar: "United States Virgin Islands" },
  { code: 'UY', dial: '+598', en: "Uruguay", ar: "Uruguay" },
  { code: 'UZ', dial: '+998', en: "Uzbekistan", ar: "Uzbekistan" },
  { code: 'VU', dial: '+678', en: "Vanuatu", ar: "Vanuatu" },
  { code: 'VA', dial: '+3906698', en: "Vatican City", ar: "Vatican City" },
  { code: 'VE', dial: '+58', en: "Venezuela", ar: "Venezuela" },
  { code: 'VN', dial: '+84', en: "Vietnam", ar: "Vietnam" },
  { code: 'WF', dial: '+681', en: "Wallis and Futuna", ar: "Wallis and Futuna" },
  { code: 'EH', dial: '+212', en: "Western Sahara", ar: "Western Sahara" },
  { code: 'YE', dial: '+967', en: "Yemen", ar: "اليمن" },
  { code: 'ZM', dial: '+260', en: "Zambia", ar: "Zambia" },
  { code: 'ZW', dial: '+263', en: "Zimbabwe", ar: "Zimbabwe" },
  { code: 'AX', dial: '+358', en: "Åland Islands", ar: "Åland Islands" },
];

/** علم الدولة كرمز تعبيري — مشتقّ من رمز ISO فلا يحتاج صورًا */
export const flagEmoji = (code: string): string =>
  code
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');

export default COUNTRIES;
